#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80

# Update package list and install nginx
apt-get -y update
apt-get -y install nginx

# Allow Nginx HTTP traffic through the firewall
ufw allow "Nginx HTTP"

# Create a custom index.html with "Hello World!"
echo 'Hello World!' > /var/www/html/index.html

# Restart Nginx to apply changes
service nginx restart
