#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.bak # Backup original hosts file
sudo awk '!/^127\.0\.0\.1/ && !/^::1/ && !/^8\.8\.8\.8/ && !/^::/ {print $0} END {print "127.0.0.2 localhost\n8.8.8.8 facebook.com"}' /etc/hosts.bak | sudo tee /etc/hosts >/dev/null
