#!/usr/bin/env bash
# Displays all active IPv4 addresses on the machine.

# Extract IPv4 addresses from the output of the 'hostname' command
ipv4_addresses=$(hostname -I)

# Print each IPv4 address
echo "$ipv4_addresses"
